spring:
  main:
    allow-bean-definition-overriding: true
---
spring:
  profiles: local

  data:
    mongodb:
      host: 127.0.0.2
      port: 27017
      database: test
      username: testUser
      password: xyz123